import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useEffect } from 'react'
import Button from '../../components/Button'

export default function Home() {
  useEffect(() => {
    fetch("./api/user")
      .then(res => res.json())
      .then(data => console.log(data));
  }, [])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          SUBROUTE
        </h1>
        
        <Button>Button</Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
